/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.autolavadosystem.view;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author carlo
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsuarios = new javax.swing.JMenu();
        submnuRols = new javax.swing.JMenuItem();
        submnuUsuarios = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        submnuClientes = new javax.swing.JMenuItem();
        submnuVehiculos = new javax.swing.JMenuItem();
        mnuServicios = new javax.swing.JMenu();
        submnuServicios = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        submnuVentas = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();
        submnuSalir = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Control de Autolavado");

        Desktop.setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuariosC.png"))); // NOI18N
        mnuUsuarios.setText("Usuarios");

        submnuRols.setText("Registrar Roles");
        submnuRols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuRolsActionPerformed(evt);
            }
        });
        mnuUsuarios.add(submnuRols);

        submnuUsuarios.setText("Registrar Usuarios");
        submnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(submnuUsuarios);

        jMenuBar1.add(mnuUsuarios);

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteC.png"))); // NOI18N
        mnuClientes.setText("Clientes");

        submnuClientes.setText("Registrar Clientes");
        submnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuClientesActionPerformed(evt);
            }
        });
        mnuClientes.add(submnuClientes);

        submnuVehiculos.setText("Registrar Vehiculos");
        submnuVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuVehiculosActionPerformed(evt);
            }
        });
        mnuClientes.add(submnuVehiculos);

        jMenuBar1.add(mnuClientes);

        mnuServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/serviciosC.png"))); // NOI18N
        mnuServicios.setText("Servicios");

        submnuServicios.setText("Registrar Servicios");
        submnuServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuServiciosActionPerformed(evt);
            }
        });
        mnuServicios.add(submnuServicios);

        jMenuBar1.add(mnuServicios);

        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ventasC.png"))); // NOI18N
        mnuVentas.setText("Ventas");

        submnuVentas.setText("Registrar Ventas");
        submnuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuVentasActionPerformed(evt);
            }
        });
        mnuVentas.add(submnuVentas);

        jMenuBar1.add(mnuVentas);

        mnuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporteC.png"))); // NOI18N
        mnuReportes.setText("Reportes");
        jMenuBar1.add(mnuReportes);

        mnuSalir.setText("Salir");

        submnuSalir.setText("Salir del Sistema");
        submnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(submnuSalir);

        jMenuBar1.add(mnuSalir);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayuda.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");
        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submnuRolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuRolsActionPerformed
        // TODO add your handling code here:
        FrmRols formRols = new FrmRols();
        Desktop.add(formRols); // Agrega el elemento al Desktop Pane
        formRols.setVisible(true);
        
    }//GEN-LAST:event_submnuRolsActionPerformed

    private void submnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuUsuariosActionPerformed
        // TODO add your handling code here:
        FrmUsuarios formUsuarios = new FrmUsuarios();
        Desktop.add(formUsuarios);
        formUsuarios.setVisible(true);
    }//GEN-LAST:event_submnuUsuariosActionPerformed

    private void submnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuClientesActionPerformed
        // TODO add your handling code here:
        FrmClientes formClientes = new FrmClientes();
        Desktop.add(formClientes); // Agrega el elemento al Desktop Pane
        formClientes.setVisible(true);
    }//GEN-LAST:event_submnuClientesActionPerformed

    private void submnuVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuVehiculosActionPerformed
        // TODO add your handling code here:
        FrmVehiculos formVehiculos = new FrmVehiculos();
        Desktop.add(formVehiculos);
        formVehiculos.setVisible(true);
    }//GEN-LAST:event_submnuVehiculosActionPerformed

    private void submnuServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuServiciosActionPerformed
        // TODO add your handling code here:
        FrmServicios formServicios = new FrmServicios();
        Desktop.add(formServicios);
        formServicios.setVisible(true);
    }//GEN-LAST:event_submnuServiciosActionPerformed

    private void submnuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuVentasActionPerformed
        // TODO add your handling code here:
        FrmVentas formVentas = new FrmVentas();
        Desktop.add(formVentas);
        formVentas.setVisible(true);
        
    }//GEN-LAST:event_submnuVentasActionPerformed

    private void submnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuSalirActionPerformed
        // TODO add your handling code here:
         salir();
         
    }//GEN-LAST:event_submnuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }
    private void salir(){
         int opcion = JOptionPane.showConfirmDialog(null,
                 "¿Seguro que deseas salir?",
                 "Confirmar Salida",
                 YES_NO_OPTION);
         if (opcion == JOptionPane.YES_OPTION){
             System.exit(0); // o dispose(); si solo quieres cerrar la ventana actual
         }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuServicios;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JMenu mnuVentas;
    private javax.swing.JMenuItem submnuClientes;
    private javax.swing.JMenuItem submnuRols;
    private javax.swing.JMenuItem submnuSalir;
    private javax.swing.JMenuItem submnuServicios;
    private javax.swing.JMenuItem submnuUsuarios;
    private javax.swing.JMenuItem submnuVehiculos;
    private javax.swing.JMenuItem submnuVentas;
    // End of variables declaration//GEN-END:variables
}
